### ISSUE TITLE
sonar-text-plugin is not working in 7.3 & 7.4 in which I am tested.

### ISSUE THREAD

**Issue by kumardharm** [gjd6640/sonar-text-plugin#11]
sonar-text-plugin is not working in 7.3 & 7.4 in which I am tested.
SonarQube not starts when I add this plugin

Note: This plugin is working fine in 6.75LTS version

**Comment by kumardharm** [comment]
Actual Error: plugin Sonar Text Plugin [text] should package its dependencies

**Comment by leojosefm** [comment]
Similar issue, the plug-in was lost when upgraded to version 7.4 from 6.7

**Comment by gjd6640** [comment]
Thanks for reporting this. I'll take a look.

**Comment by gjd6640** [comment]
Ok. I have made some updates that should do the trick. Please read the warning statement on the release and make sure that you do appropriate backups and testing.

https://github.com/gjd6640/sonar-text-plugin/releases/tag/2.0
