### ISSUE TITLE
The plugin does not work with SonarQube 9.3.0

### ISSUE THREAD

**Issue by ducquang92** [gjd6640/sonar-text-plugin#21]
Hi,
After upgrading to SonarQube 9.3.0, the plugin cause the following error:
```
Startup failed: Plugins can't be loaded. See web logs for more information

Web server startup failed: Found a plugin 'Sonar Text Plugin' in the directory 'extensions/plugins' with the same key [text] as a built-in feature 'Text file Code Quality and Security'. Please remove 'extensions/plugins/sonar-text-plugin-1.1.5.jar'.
```

Apparently there is a new build-in feature with the key "text" in the new version, so it causes the key conflict.
Could you please look into how to fix it?

**Comment by gjd6640** [comment]
Thank you for pointing this out. I was not previously aware of this issue. Probably our first step needs to be to inform the SonarSource team. They may want to deconflict on their end. Either way they’ll have good advice on how best to negotiate through this. I’ll try to start that conversation with them in the next few days and will post a link to that here.

**Comment by gjd6640** [comment]
Request posted. I'm looking forward to hearing their perspective.

https://community.sonarsource.com/t/requesting-advice-for-resolving-conflict-in-sq-v9-3-between-builtin-text-language-and-the-community-sonar-text-plugin/58960

**Comment by gjd6640** [comment]
Please try out [release v2.2.0](https://github.com/gjd6640/sonar-text-plugin/releases/tag/v2.2.0). Let me know if that doesn't fix things for you.

As always, be sure to back up your database beforehand and test the upgrade in a non-production environment to verify that your custom rules survive the upgrade.
